const INCENSE_TYPES = [
  'Advice',
  'Artistic Inspiration',
  'Beauty',
  'Caring & Warmth',
  'Creativity',
  'Challenge Spirit',
  'Connecting People',
  'Compassion',
  'Courage',
  'Carrot & Stick',
  'Craziness',
  'Faith & Belief',
  'Generosity',
  'Humor & Fun',
  'Humbleness',
  'Healing',
  'Integrity',
  'Intellectual Inspiration',
  'Justice',
  'Kindness',
  'Love',
  'Leadership',
  'Passion',
  'Positivity',
  'Protection',
  'Peace',
  'Purity',
  'Royalty',
  'Sacrifice',
  'Support',
  'Trust',
  'Wisdom',
];

export default INCENSE_TYPES;
